### ISSUE TITLE
www. should work

### ISSUE THREAD

**Issue by calpaterson** [calpaterson/quarchive#47]
# Description

www.quarchive.com does not work

# Steps to reproduce

1. Navigate to https://www.quarchive.com

# Expected result

See quarchive (after a redirect)

# Actual result

Can't connect

# Additional details

**Comment by samlader** [comment]
Looks like a missing DNS record? 😉 

<img width="298" alt="Screen Shot 2020-12-20 at 23 46 24" src="https://user-images.githubusercontent.com/6299632/102727453-a073fa80-431d-11eb-87ac-4e2678b1ad1d.png">

**Comment by calpaterson** [comment]
Yep!  And perhaps some nginx config :)
